<?php
	$linkAppPage = $this->linkAppPage;
	if($linkAppPage != "")
	{
		echo "<script>chuyenTrang('$linkAppPage');</script>";
		//echo "<a href='javascript:;' onclick = \"chuyenTrang('$linkAppPage')\">Click Here</a>";
	}
	else
	{
		$linkNoiDung = $this->linkNoiDung;
		if($linkNoiDung != "")
		{
			echo "<script>chuyenTrang('$linkNoiDung');</script>";
			//echo "<a href='javascript:;' onclick = \"chuyenTrang('$linkNoiDung')\">Click Here</a>";
		}
		else
		{
			echo "Cảm ơn bạn đã xem ứng dụng. Chúc bạn 1 ngày tốt lành :D";
		}
		
	}

?>