<?php

	$config = $this->config;
?>
<p class="title_page">Cấu hình Apps</p>
<form action="<?php echo APP_DOMAIN ?>/admin/config/xulyconfig" method="post" enctype="multipart/form-data" onsubmit="cauhinhapp();">

<table class="table_config" border="1">
	<tr>
		<td width="200">Banner</td>
		<td>
			<input type="file" name="banner" id="" size="30" />
			<?php if(@$config[0]['banner']!=""){ ?>
				<img src="<?php echo APP_DOMAIN ?>/public/images/banner/<?php echo $config[0]['banner'] ?>" width="500" alt=""/>
			<?php } ?>
		</td>
	</tr>
	<tr>
		<td>Footer</td>
		<td><input class="input_style" type="text" name="footer" value="<?php echo @$config[0]['footer']?>" /></td>
	</tr>
	<tr>
		<td>Số lần like</td>
		<td><input class="input_style" type="text" name="solanlike" value="<?php echo @$config[0]['solanlike']?>" /></td>
	</tr>
	<tr>
		<td></td>
		<td><input type="submit" name="luucauhinh" value="Lưu cấu hình"/></td>
	</tr>
</table>
</form>
