		<div style="position: absolute; top: -10000px; height: 0px; width: 0px;"><div></div></div>
			<div class="header">
				<div id="header">
					<div class="header_left">
						<a class="header_logo" href="" target="_blank">
						<img  src="<?php echo $this->baseUrl ('application/templates/giaodien_admin/images/logo.png') ?>" />		
						</a>
					</div>
					<div class="header_center">
						<div class="logo_text">
							<a>ISHALI MEDIA</a>
						</div>
						<div class="shareUrl">
							Apps Store
						</div>
					</div>
					<div class="header_right">
						<div id="public_section" class="swicth_section">
						</div>
						 
						<div class="manage_pages">
							<?php echo $this->list_pages ?>
						</div>
					</div>
				</div>
			</div>