<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML+RDFa 1.0//EN" "http://www.w3.org/MarkUp/DTD/xhtml-rdfa-1.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://www.facebook.com/2008/fbml" xmlns:og="http://opengraphprotocol.org/schema/"><head>
<title>ISHALI STORE</title>  
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<link rel="stylesheet" type="text/css" href="canvas_admin.css">
<script>
	var taaa = {};
	taaa.appdomain = "<?php echo APP_DOMAIN ?>";
	taaa.fbappdomain = "<?php echo FB_APP_DOMAIN ?>";
</script>

<script src="<?php echo APP_DOMAIN . '/public/js/modal.popup.0.2.js'; ?>" type="text/javascript"></script>
<?php
	echo $this->headLink ()
			->appendStylesheet ( $this->baseUrl ('application/templates/giaodien_admin/css/ishali_admin.css'))
			->appendStylesheet ( $this->baseUrl ('application/templates/giaodien_admin/css/jquery-ui.css'))
			
			->appendStylesheet ( $this->baseUrl ('application/templates/giaodien_admin/css/colorpicker.css'))
			;
			

	echo $this->headScript ()
			->appendFile ( $this->baseUrl ('/application/templates/giaodien_admin/js/jquery-1.8.0.min.js') )
			
			->appendFile ( $this->baseUrl ('/application/templates/giaodien_admin/js/aj.js') )
			->appendFile ( $this->baseUrl ('/application/templates/giaodien_admin/js/script.js') )
			->appendFile ( $this->baseUrl ('/application/templates/giaodien_admin/js/list_tab.js') )
			
			
			->appendFile ( $this->baseUrl ('/application/templates/giaodien_admin/js/colorpicker.js') )
			->appendFile ( $this->baseUrl ('/application/templates/giaodien_admin/js/eye.js') )
			->appendFile ( $this->baseUrl ('/application/templates/giaodien_admin/js/layout.js') )
			
			
			//->appendFile ( $this->baseUrl ('/application/templates/giaodien_admin/js/jquery.min.js') )
		//	->appendFile ( $this->baseUrl ('/application/templates/giaodien_admin/js/jquery-ui.min.js') )
			

			->appendFile ( $this->baseUrl ('/public/ckeditor/ckeditor.js') )
			->appendFile ( $this->baseUrl ('/public/ckfinder/ckfinder.js') )
		
			;
		
		?>
        
		<script>
            $(function(){
              center()//gọi hàm mới load web
                $(window).resize(function(){center()})//gọi hàm khi resize
        		//alert($(window).width());
        		//alert($('#thongbao').width());
              function center(){
                $('#thongbao').css({left:($(window).width()-$('#thongbao').width())/2,top:150})
              }
            })
          </script>
		
</head>
<body>
	<div id="bg_thongbao"></div>
	<div id="thongbao"></div>
		<?php  echo $this->render('_header.phtml')?>
	<div id="" class="wrapper">
	<div class="container">

		<?php
		$controllerName = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
		
		$index = ''; $config = ''; $changepass = ''; $chonpagelike = ''; $sapxeppagelike = ''; $noidungchiase = '';
		if($controllerName == 'index')
			$index = 'active';
		if($controllerName == 'config')
			$config = 'active';
		if($controllerName == 'changepass')
			$changepass = 'active';
		if($controllerName == 'chonpagelike')
			$chonpagelike = 'active';
		if($controllerName == 'sapxeppagelike')
			$sapxeppagelike = 'active';
		if($controllerName == 'noidungchiase')
			$noidungchiase = 'active';
		if($controllerName == 'baivietcuapage')
			$baivietcuapage = 'active';
		?>
		
		<div class="list_menu">
			<?php 
				if(isset($_SESSION['iduseradmin']))
				{
			?>
			<ul>
				<li class="menu <?php echo $index ?>">
					<a style="display: inline;" href="<?php echo ROOT_DOMAIN ?>/admin" target="_top">Home</a>
				</li>
				<li class="menu <?php echo $config ?>">
						<a style="display: inline;" class="" href="<?php echo ROOT_DOMAIN ?>/admin/config"  target="_top">Cấu hình</a>
				</li>
				<li class="menu <?php echo $chonpagelike ?>">
						<a style="display: inline;" class="" href="<?php echo ROOT_DOMAIN ?>/admin/chonpagelike"  target="_top">Chọn page like</a>
				</li>
				<li class="menu <?php echo $sapxeppagelike ?>">
						<a style="display: inline;" class="" href="<?php echo ROOT_DOMAIN ?>/admin/sapxeppagelike"  target="_top">Sắp xếp page</a>
				</li>
				<li class="menu <?php echo $noidungchiase ?>">
						<a style="display: inline;" class="" href="<?php echo ROOT_DOMAIN ?>/admin/noidungchiase"  target="_top">Nội dung chia sẻ</a>
				</li>
				<li class="menu <?php echo $baivietcuapage ?>">
						<a style="display: inline;" class="" href="<?php echo ROOT_DOMAIN ?>/admin/baivietcuapage"  target="_top">Bài viết của page</a>
				</li>
				<li class="menu <?php echo $changepass ?>">
						<a style="display: inline;" class="" href="<?php echo ROOT_DOMAIN ?>/admin/changepass"  target="_top">Đổi mật khẩu</a>
				</li>
				<li class="menu">
						<a style="display: inline;" class="" onclick="DangXuat();" href="javascript:;" >Đăng Xuất</a>
				</li>

			</ul>
			<?php
				}
			?>
				
	<!--			
			<?php
				$list_page = $_SESSION['list_page'];
				if($list_page!=0)
				{
					$store = App_Models_StoreModel::getInstance();
					$lpage = $store->GetPageFbByIdUserFB();
					@$idpage = $_SESSION['idpage'];
					if(count($lpage) > 0)
					{
				?>
					<div class="list_page">
						<select id="slist_page" class="select_list_page" onchange="ChangeListPage(document.getElementById('slist_page').value)">
							<option value="0">Chọn Page cần thao tác</option>
							<?php
								for($i=0; $i<count($lpage); $i++)
								{
							
								$idpagefb = $lpage[$i]['id_fb_page'];
								$namepafefb = $lpage[$i]['page_name'];
								if($idpagefb == $idpage)
								{
									echo "<option selected='selected' value='$idpagefb'>$namepafefb</option>";
								}
								else
									echo "<option value='$idpagefb'>$namepafefb</option>";
								}
							?>
						</select>
					</div>
				<?php 
					} 
				}
				?>
		-->
		</div>
		
		<div class="contents">					
			<div class="galleries_contents">	
				<div id='quanlidanhsachtrang' style="display: block"  >
					<?php echo $this->layout()->content; ?>	
				</div>
			</div>
		</div>
		<?php  echo $this->render('_footer.phtml')?>	
	</div>
</body>
</html>