<?php
	$pageInfo = $this->pageInfo;
	$pageInfo = $pageInfo[0];
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<link type="text/css" rel="stylesheet" href="<?php echo APP_DOMAIN . '/application/layouts/'. $pageInfo['templates'] .'/css/main.css'; ?>"></link>
<link type="text/css" rel="stylesheet" href="<?php echo APP_DOMAIN . '/application/layouts/'. $pageInfo['templates'] .'/css/style.css'; ?>"></link>
<script type="text/javascript" src="<?php echo APP_DOMAIN . '/application/layouts/'. $pageInfo['templates'] .'/js/jquery-1.8.0.min.js'; ?>"></script>
<script type="text/javascript" src="<?php echo APP_DOMAIN . '/application/layouts/'. $pageInfo['templates'] .'/js/likepage.js'; ?>"></script>
<script>
	var taaa = {};
	taaa.appdomain = "<?php echo APP_DOMAIN ?>";
	taaa.fbappdomain = "<?php echo FB_APP_DOMAIN ?>";
</script>

<title>Apps Like Nhieu Page</title>

</head>

<body>

	<div id="container">
    	<div id="banner">
		</div><!--End #banner-->
    	<div id="main_nav">
        </div><!--End #main_nav-->
        <div id="content">
        	<?php echo $this->layout()->content; ?>
        </div><!--End #content-->
        <div id="footer">Powered by ISHALI MEDIA</div><!--End #footer-->
        
	</div><!--End #container-->
	
</body>
</html>
